// src/components/weeks/week1/AssignmentInstructions.tsx

import React from 'react';
import { Container, Typography, Box, List, ListItem, ListItemText, Paper } from '@mui/material';
import { CopyBlock, dracula } from 'react-code-blocks';

const AssignmentInstructions: React.FC = () => {
    return (
        <Container maxWidth="md">
            <Box my={4}>
                <Typography variant="h4" component="h1" gutterBottom>
                    Week 1 Assignment: Basic Planet Generation
                </Typography>
                <Typography variant="body1" paragraph>
                    In this assignment, you will create a simple Python script to generate a list of planets with randomly generated attributes. Follow the steps below to complete the assignment and test your code.
                </Typography>

                <Typography variant="h5" component="h2" gutterBottom>
                    Steps to Complete the Assignment
                </Typography>
                <List>
                    <ListItem>
                        <ListItemText primary="1. Create a new Python file called `planet_generation.py`." />
                    </ListItem>
                    <ListItem>
                        <ListItemText primary="2. Define a function called `generate_planet` that creates a planet with random attributes (e.g., name, size, color, orbit distance, and orbital period)." />
                    </ListItem>
                    <ListItem>
                        <ListItemText primary="3. Define a function called `generate_solar_system` that generates a list of planets." />
                    </ListItem>
                    <ListItem>
                        <ListItemText primary="4. Print the list of planets generated by the `generate_solar_system` function." />
                    </ListItem>
                </List>

                <Typography variant="h6" component="h3" gutterBottom>
                    Example Code
                </Typography>
                <CopyBlock
                    text={`
import random

def generate_planet():
    names = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
    colors = ["gray", "yellow", "blue", "red", "orange", "pale yellow", "light blue", "deep blue"]
    name = random.choice(names)
    size = random.uniform(0.5, 10.0)  # Arbitrary size units
    color = random.choice(colors)
    orbit_distance = random.uniform(0.4, 30.0)  # Arbitrary distance units
    orbital_period = random.uniform(88, 60190)  # Arbitrary period units in days

    return {
        "name": name,
        "size": size,
        "color": color,
        "orbit_distance": orbit_distance,
        "orbital_period": orbital_period
    }

def generate_solar_system(num_planets=8):
    return [generate_planet() for _ in range(num_planets)]

if __name__ == "__main__":
    solar_system = generate_solar_system()
    for planet in solar_system:
        print(planet)
          `}
                    language="python"
                    theme={dracula}
                    codeBlock
                />

                <Typography variant="h5" component="h2" gutterBottom>
                    Testing Your Code
                </Typography>
                <Typography variant="body1" paragraph>
                    To test your code, you can use the command line. Follow the steps below to run your Python script and verify that it works correctly.
                </Typography>
                <List>
                    <ListItem>
                        <ListItemText primary="1. Open a terminal or command prompt." />
                    </ListItem>
                    <ListItem>
                        <ListItemText primary="2. Navigate to the directory where your `planet_generation.py` file is located." />
                    </ListItem>
                    <ListItem>
                        <ListItemText primary="3. Run the following command to execute your script:" />
                    </ListItem>
                </List>
                <Paper elevation={3} sx={{ padding: 2, backgroundColor: '#f5f5f5' }}>
                    <CopyBlock
                        text="python planet_generation.py"
                        language="bash"
                        theme={dracula}
                        codeBlock
                    />
                </Paper>
                <Typography variant="body1" paragraph>
                    You should see the list of generated planets printed in the terminal. Verify that the output matches the expected format and that the attributes are generated correctly.
                </Typography>

                <Typography variant="h5" component="h2" gutterBottom>
                    Submission Instructions
                </Typography>
                <Typography variant="body1" paragraph>
                    Once you have completed the assignment and tested your code, submit your `planet_generation.py` file through the course's submission portal. Make sure your code is well-documented and follows best practices.
                </Typography>
            </Box>
        </Container>
    );
};

export default AssignmentInstructions;
