// src/components/weeks/week1/Exercise3.tsx
import React from 'react';
import { Typography, Box, List, ListItem, ListItemText } from '@mui/material';
import { CopyBlock, dracula } from 'react-code-blocks';

const Exercise4: React.FC = () => {
    return (
        <Box my={4}>
            <Typography variant="h5" component="h2" gutterBottom>
                Exercise 4: Print the List of Planets
            </Typography>
            <Typography variant="body1" paragraph>
                In this exercise, you will print the list of planets generated by the `generate_solar_system` function.
            </Typography>
            <List>
                <ListItem>
                    <ListItemText primary="1. In your `planet_generation.py` file, add code to print the list of planets generated by the `generate_solar_system` function." />
                </ListItem>
            </List>
            <Typography variant="h6" component="h3" gutterBottom>
                Template Code
            </Typography>
            <CopyBlock
                text={`
if __name__ == "__main__":
    solar_system = generate_solar_system()
    for planet in solar_system:
        print(planet)
                `}
                language="python"
                theme={dracula}
                codeBlock
            />
        </Box>
    );
};

export default Exercise4;
